name: hops
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOSTS=/data/hosts.yml
    volumes:
      - /home/leo/hops/data:/data
